### ISSUE TITLE
Problem compiling with PostgreSQL on Ubuntu 16.04

### ISSUE THREAD

**Issue by vitalik-rnd** [Ericsson/CodeCompass#308]
Dear all,

I'm trying to compile CodeCompass on Ubuntu 16.04 with the PostgreSQL.
I have followed the your [Dependency and Requirement guide](https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md).

CodeCompass's compilation fails with errors like these:
`undefined reference to odb::pgsql::query_base::append(char const*, char const*)`

`undefined reference to odb::pgsql::query_base::append(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)`

`sourcemanager.cpp:(.text+0x172e): undefined reference to odb::pgsql::query_param::~query_param()'
CMakeFiles/CodeCompass_parser.dir/src/sourcemanager.cpp.o: In function odb::pgsql::query_param_impl<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, (odb::pgsql::database_type_id)10>::~query_param_impl()':`

At the end I am getting this error message:
`Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

Full compilation and error log can be found [here](https://pastebin.com/RGyHDUwy) (PasteBin).

I have successfully, compiled CodeCompass using SQLite but at the end I did not manage to make it fully work. I posted a question about it [here](https://github.com/Ericsson/CodeCompass/issues/290)

Any idea how to make to compilation work?
Please pardon me if this is not the right place to ask such questions.
Thank you very much for your help

**Comment by bruntib** [comment]
Hi,

It seems to me that there is some problem with ODB installation. When you compile CodeCompass, it must be given as a cmake parameter which database system you want to use:
```
cmake -DDATABASE=sqlite ...
or
cmake -DDATABASE=pgsql ...
```
ODB can handle both of these, however, these have to be compiled and installed as separate libraries. The CodeCompass user guide describes how to build and install them. Note that both ODB database drivers can go to the same installation directory. So as a first step, please verify that the PostgreSQL ODB driver is successfully compiled and installed to the specific directory.

Another idea is to remove completely the CodeCompass build directory and rerun cmake command from scratch. If you had a previous compilation with SQLite, then its configuration might have got stuck. I've already seen such a behavior.

And at the end don't forget to install CodeCompass with `make install` as the final step.

Note, that from a given Ubuntu version the package repository contains ODB as well. So it can also be a solution to install ODB development package to your system. At the time of writing CodeCompass documentation ODB was not found in Ubuntu repositories. https://packages.ubuntu.com/cosmic/odb

I hope I could help. If you still have problems, please let us know and let's debug further.

**Comment by bruntib** [comment]
Hi,

This long java exception always appears. We should fix this some time. However, this shouldn't cause any problem.

Could you please paste the `CodeCompass_parse ...` command which you used before starting the server?

**Comment by vitalik-rnd** [comment]
Hi,
> 
> Could you please paste the `CodeCompass_parse ...` command which you used before starting the server?

Here it is:
`./keepalive ./CodeCompass_parser   -d "pgsql:host=localhost;port=5432;user=compass;password=cc;database=mydatabase"   -w ~/cc/workdir   -n life   -i ~/code_for_analysis/life/compilation_commands.json   -i ~/code_for_analysis/life   -j 4`

Full output can be found [here](https://pastebin.com/BSgEN8hy)

Thanks

**Comment by bruntib** [comment]
Hi,

Could you please try to do a forced reparse? This can be done by providing `-f` flag to the parser.

**Comment by vitalik-rnd** [comment]
Hi, 
The output of the forced reparse available [here](https://pastebin.com/9BenaDhX).
The problem still exists.

Thanks

**Comment by bruntib** [comment]
According to the log output no C++ files were parsed by the C++ parser. Could you check the content of compilation_commands.json if it really describes the compilation of your project?

**Comment by vitalik-rnd** [comment]
> According to the log output no C++ files were parsed by the C++ parser. Could you check the content of compilation_commands.json if it really describes the compilation of your project?

Strangely, my compilation_commands.json was empty. I remember that when I created it for the first time it was not empty. I probably messed it up somehow.
I have regenerated it again, parsed the files and now I see that the files are marked with green, (Fully parsed) markings, which is great :)

When I click on the file, sometimes the following error message appears:
`Uncaught TypeError: Cannot read property 'id' of undefined
    at Object._markUsages (Text.js?1545144460649:433)
    at Object._eventHandler (Text.js?1545144460649:408)
    at Text.js?1545144460649:256
    at signal (codemirror.js:1165)
    at signalDOMEvent (codemirror.js:1174)
    at CodeMirror.onMouseDown (codemirror.js:7271)
    at HTMLDivElement.<anonymous> (codemirror.js:3906)`

In some places when I click on "Go to definition",
The following warning message appears in console log, and nothing happens (no jump occurs):
`Can't find definition to this node`

Sometimes "Go to definition" do works

@bruntib, thank you so much for your help.

**Comment by bruntib** [comment]
It is possible that the definition is not present in your project. For example if you have a translation unit which contains only the declaration of a function and in your build system you skip the linking process then CodeCompass can show this as "Fully parsed".
```.cpp
myfile.cpp
----------
void f(); // Only a declaration
void g()
{
  f(); // No definition of this function.
}

g++ -c myfile.cpp
```
Could you check if the source file which contains the definition of that function is compiled according to the compilation_commands.json file?

**Comment by vitalik-rnd** [comment]
Hi,
This little test project contains 3 files. "life.cpp", "world.cpp" and "world.hpp".

My compilation_commands.json file contains two cpp files:
```
[
        {
                "directory": "/home/cc/code_for_analysis/life",
                "command": "g++ -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include$
                "file": "/home/cc/code_for_analysis/life/life.cpp"
        }
        ,
        {
                "directory": "/home/cc/code_for_analysis/life",
                "command": "g++ -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include$
                "file": "/home/cc/code_for_analysis/life/world.cpp"
        }
]
```
life.cpp includes "world.hpp" file.

In CodeCompass, all three files ("life.cpp", "world.cpp" and "world.hpp") marked with green (Fully parsed) mark.

When I try to go to definition of `life::world::write` (from "life.cpp" file) which exist in "world.cpp" file, I am unable to do it and I can see the following warning message apears in the browser's console log:
`Can't find definition to this node`

Thank you

**Comment by bruntib** [comment]
Hi,

Could you send us the project files? If this is the case then this will be a bug.

**Comment by vitalik-rnd** [comment]
Hi,
Sure, I have uploaded the project [here](https://file.io/Jy5bCj)

Thanks

**Comment by bruntib** [comment]
Hi,

I have found a serous bug in CodeCompass which causes this problem. I'll create an issue on it and we'll fix it. Until then you can workaround the problem: in your compilation_database.json file there are two JSON objects. Both are referring to a compilation action and both compilation commands contain both .cpp files. You should edit the JSON file so each g++ command contains only one .cpp file, the one which is indicated in the "file" attribute.

Thanks for the report, this was very useful and important!

**Comment by vitalik-rnd** [comment]
@bruntib,
Great, thanks checking this out
